### ISSUE TITLE
Create hyperparameter table and model diagram during render

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#157]
RE: slack discussion we had with @BenjaminBossan I'm in favor of creating the table during rendering rather than initially creating the `Card` instance. I made it back then like that because we weren't having a separate function for rendering, and I wanted all cards to by default have this table and plot of the model as well. If the model is replaced by another the table will not match with the one that was created during creation of the card. 

- [ ] Move table
- [ ] Move plot

**Comment by BenjaminBossan** [comment]
Just so we don't forget, the same logic applies to the model diagram.

**Comment by merveenoyan** [comment]
@BenjaminBossan @adrinjalali I looked at the code again and realized that given model is an attribute of the card it is _okay_ if we create the table and plot during card creation and user needs to know that if they want to version a model, they should update the card as well. WDYT?

**Comment by BenjaminBossan** [comment]
Just to avoid any confusion, we're talking about a situation like this, right?

```python
model0 = ...
model1 = ...
card = Card(model0, ...)  # creates _hyperparameter_table and _model_diagram attributes
...
card.model = model1
card.save(...)  # creates hyperparam table and model diagram of model0, not model1
```

So I'd say we should

1. make `card.model` private so that users don't overwrite the attribute, or 
2. create the hyperparam table and model diagram lazily, i.e. only when `card.save` is called

> user needs to know that if they want to version a model, they should update the card as well

That would be more or less achieved with option 1 (not explicitly, but by convention).
