### ISSUE TITLE
Add serialization format to config.json

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#228]
We should add which format model was serialized with in config.json so that we could update the example snippet the users can follow both in model card and 🤗Hub repository.

**Comment by adrinjalali** [comment]
What would the API look like?

**Comment by merveenoyan** [comment]
@adrinjalali given we initialize the repository after model is saved, either `hub_utils.init()` should infer the model type (maybe try to call a skops model-specific method) without user entering it or we could put a parameter to it, saying
`hub_utils.init(..., skops_format = True)` and set it to `True` by default. Not sure if it's the best though.

**Comment by merveenoyan** [comment]
@adrinjalali @BenjaminBossan WDYT of this?

**Comment by BenjaminBossan** [comment]
I don't have a preference, whatever you think works best. The only thing I'd avoid is:

`hub_utils.init(..., skops_format = True)`

because we might have more formats in the future than pickle vs skops, e.g. ONNX. So if we want to pass it explicitly, it should be something like

`hub_utils.init(..., save_format=X)`

where `X` is "pickle" or "skops" for the time being.

**Comment by adrinjalali** [comment]
We can also have the default value of the arg to be `auto`, and do this mapping  from extension to format:

- `.skops` -> `skops`
- `.pkl`, `.pickle`, `.joblib` -> pickle

**Comment by BenjaminBossan** [comment]
@merveenoyan this is resolved via #242 right?
