### ISSUE TITLE
Support older versions of huggingface_hub

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#25]
Currently we support the latest version of `huggingface_hub` due to `upload_folder`. `skops` needs to support older versions. Maybe we could use `upload_file` instead if we want to keep using `HfApi`?

**Comment by osanseviero** [comment]
Why does `skops` need to support older versions?

**Comment by adrinjalali** [comment]
Because having tight dependencies makes it hard for users to install multiple integrations. For instance, it would make it impossible for users to have an environment which has `skops` and Spacy's integration together.

But this is not trivial since we can't simply vendor `upload_folder` since it depends on `create_commit` which itself is a new feature.
