### ISSUE TITLE
Injecting variables after creation

### ISSUE THREAD

**Issue by merveenoyan** [skops-dev/skops#31]
Opening discussion for [this comment](https://github.com/skops-dev/skops/pull/26#pullrequestreview-1038568847) by @adrinjalali.

As with the current implementation in `modelcards` library, it’s not really possible to inject values to jinja template after the card creation (I also talked to @nateraw  and he told me it’s made to be this way).

I looked at jinja’s own docs and saw the rendering takes place once with a dictionary you pass in (it takes place when we initialize the RepoCard) so below is how `modelcards` library uses render as well like below:
```
content = jinja2.Template(Path(template_path).read_text()).render(
            card_data=card_data.to_yaml(), **template_kwargs
        )
```
so technically you can’t inject anything after you initialize the model card. as of currently implementation we have in skops, it’s not really possible to inject things after creation as well.

So I thought of having a separate card class made for skops and separate initialization and letting user pass attributes and at the end, get these attributes and pass as a dict to RepoCard template when the user calls `save()`.
so the UX is a bit like this (which doesn't change anything except for adding variables during creation)

```
#below card class is our card class
model_card = card.create_model_card(
    model,
    card_data=card_data,
    template_path=“./skops/skops/card/default_template.md”,
    limitations=limitations,
    model_description=model_description,
)
card.metrics = some_metrics
card.save(path) # this method will initialize `RepoCard` class of modelcards, pass the class attributes as dictionary to that, renders (which is done in `modelcards`), and save the card
```

Maybe we can let user add things as they wish to the template, meaning they can add as many plots as they wish by simply editing the markdown, like below:

```
card.roc_plot = roc_plot # this normally doesn't exist in template, we'll add it at the end with attribute setting
card.save(path)
```

WDYT? @adrinjalali @BenjaminBossan

**Comment by BenjaminBossan** [comment]
(note: this could have been added to #29 :)

> so technically you can’t inject anything after you initialize the model card
> So I thought of having a separate card class made for skops and separate initialization and letting user pass attributes

I think the initialization should not directly create the model card, so that it can be built up incrementally if needed. However, I would discourage setting attributes directly, so no `card.metrics = some_metrics`. I think it's almost inevitable that this will eventually result in custom setters and getters, so let's make it an explicit method call for the user, as suggested by Adrin.

> card.save(path)

As mentioned in #29, we should think about whether we want this code to be a thin wrapper around Nate's model cards or a more abstract class that could support different model card implementations and formats.

> Maybe we can let user add things as they wish to the template

Also as discussed in #29, I think this is an important design decision that should be decided on early. My intuition tells me that we should not restrict the user in only allowing things we thought of, but we should also not allow arbitrary objects (since we wouldn't know how to convert them to cards). So probably we want to have scalars, plots and tables to begin with?

**Comment by merveenoyan** [comment]
Closing this in favor of #29
