### ISSUE TITLE
RFC Warn users for missing slots of the model card template.

### ISSUE THREAD

**Issue by adrinjalali** [skops-dev/skops#51]
xref: https://github.com/skops-dev/skops/pull/37/files#r928169418

We should decide if we want to warn users if the user fails to pass any or certain fields of the model card. Previously we have discussed that we should have very few mandatory fields in the card to reduce the entry barrier.

We could warn the users about all or some of the fields, or leave it to the user since the missing fields are rendered as missing in the `README.md` file anyway, i.e. the user would see that they are missing.

cc @meg-huggingface @osanseviero @skops-dev/maintainers

**Comment by osanseviero** [comment]
Also cc @nateraw as I was wondering if this could be implemented directly as a param within the `modelcards` utilities (e.g. `mode="strict"` vs `mode="warn"` vs `mode="light"` or something like that, and then each library user could determine how they want to handle this.

**Comment by adrinjalali** [comment]
@BenjaminBossan this can be achieved easily now, right?

**Comment by BenjaminBossan** [comment]
There are ways to achieve that, yes. Personally, I don't think it's super useful though.

**Comment by nateraw** [comment]
Yea totally possible to do this in hf_hub version...would want to default to being quiet though, so as to not overwhelm the terminal of users by default (as I'm guessing in many cases they will leave many jinja template vars blank). 

imo I don't know how helpful this is though (in terms of dev effort vs payoff). Mostly because once you see the rendered card its fairly obvious which vars you didn't pass. just my two cents tho - would love other opinions. 😄
